discord:
  botkey: "enternewkeylater"
  channel: "741565641521365063"
  qlength: 64
  waitms: "500ms"

ironrealms:
  apiurl: "https://api.achaea.com"

#database:
 # connection: "user=gregent password=password dbname=ada-bot sslmode=disable"

settingsfile: settings.yaml
