discord:
  botkey: "NzgwMzEwNzQ0NTYxNDgzNzk2.X7tPAg.DfmKaUjMCBKHyq6nq3HbId017dQ"
  channel: "741565641521365063"
  qlength: 64
  waitms: "500ms"

ironrealms:
  apiurl: "https://api.achaea.com"

database:
  connection: "user=carsqn password=|RGqfx5rvAS^+[J dbname=ada-bot sslmode=disable"

settingsfile: settings.yaml
